### ISSUE TITLE
if no profile, should use default

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/aws-cli-utils#5]
for both ec2 and log, I get no results when doing `aws-cli ec2` and `aws-cli ec2 --profile default`

**Comment by ecwillis** [comment]
In the specs, the appropriate option for the AWS profile, is `--environment`.

`--profile` is reserved for the Log Profile option, (or other forthcoming profile service params).

**Comment by jgallen23** [comment]
lame, I can't spell that

**Comment by ecwillis** [comment]
One sec... working it out in my head as well

**Comment by jgallen23** [comment]
wait, what is log profile?

**Comment by ecwillis** [comment]
Nevermind. To many variables. I got Log Groups and Profile confused.
